# Generated by Django 5.0.3 on 2024-04-01 20:32

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('radioapp', '0002_cliente_fornitore_acquisto_vendita_prodotto_and_more'),
    ]

    operations = [
    ]
