# Generated by Django 5.0.3 on 2024-04-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioapp', '0005_remove_fornitore_partita_iva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisto',
            name='stato',
            field=models.CharField(default='In arrivo', max_length=30),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='capacità',
            field=models.IntegerField(),
        ),
    ]
