# Generated by Django 5.0.3 on 2024-04-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioapp', '0006_acquisto_stato_alter_prodotto_capacità'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='stato',
            field=models.CharField(default='In arrivo', max_length=20),
        ),
    ]
