# Generated by Django 5.0.3 on 2024-04-06 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioapp', '0007_alter_prodotto_stato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisto',
            name='codice_fornitore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='radioapp.fornitore'),
        ),
    ]
